'use strict';

let hagridsHut = new LocationFeature('hagridsHut', 'Hagrid\'s hut', 'Deciding that the Forbidden Forrest might be the best place to start you and Esmeralda carefully make your way down to the back of Hagrid\’s hut and peer into the dark forrest. It\’s off limits to students for a reason but you decide to take your chances. What\’s the worst that could happen? The path ahead of you forks into three directions rather quickly. Which way will you go?', ['Esmeralda is sniffing off to the right… maybe she is just hunting for truffles though? Follow Esmeralda.', 'hippogryphFlight'], ['You see some hoof prints off to the right. Should you follow them?', 'centaurFirenze'], ['Boldly forward is always a great way to start. Go straight ahead.', 'bowtruckleTree'], ['Return to the second floor girls lavatory', 'home']);



let leakyCauldron = new LocationFeature('leakyCauldron', 'The Leaky Cauldron', 'There\’s only one place you can think of that would possibly have a poisonous candle, Diagon Alley. It\’s going to be risky but you\’ll have to sneak out and take your broom to London. Maybe if you stay above the clouds you can avoid being seen by muggles? You get Esmeralda to climb into your knapsack and grab your Firebolt. The next thing you know you are entering Diagon Alley through the wall behind the Leaky Cauldron. Where do you look first?', ['Flourish and Blots, someone may know where you can get a candle', 'flourishBlots'], ['Slug and Jiggers Apothecary, after-all they do sell potion supplies…', 'slugjig'], ['Florean Fortescue\’s Ice Cream. The ride over was really tiring and you could use a pick me up.', 'floreanFortescue'], ['Return to the 2nd floor girls lavatory', 'home']);


let flourishBlots = new LocationFeature('flourishBlots', 'Flourish and Blots', 'You pass through the door of Flourish and Blots and the bell on the door jingles behind you. You try to act casual, checking out books with your pig trailing behind you as you approach the counter. You ask the older witch at the counter if she knows where you might be able to purchase a poisonous candle for potions class. She gives you a cold stare and says \“No reputable shop would sell an underage student a poisonous candle without a parent present\”. You try to tell her your parents are outside but she isn\’t buying it. You leave the shop and look up the road for another option.', ['Slug and Jiggers Apothecary, after-all they do sell potion supplies…', 'slugJig'], ['Florean Fortescue\’s Ice Cream. The ride over was really tiring and you could use a pick me up.', 'floreanFortescue'], ['Go back to the Leaky Cauldron', 'leakyCauldron'], ['Return to the 2nd floor girls lavatory', 'home']);

let slugJig = new LocationFeature('slugJig', 'Slug and Jiggers Apothecary', 'Walking in to Slug and Jiggers Apothecary you smell the pungent odor of Bubotuber Pus. Scanning the heavily stocked shelves you feel hopefully that this might be the place to find your candle. A wrinkled old wizard in red robes ask \“What can I get for you today young potions master?\” You ask for a poisonous candle and the wizard gives you a concerned look and replies \“We don’t stock the types of supplies that are used in the darker arts in our store.\” You lift Esmeralda up to the counter, her pink glasses askew, and try to explain about your pig friend. The wizard seems to soften a little and says \“We do not carry such supplies but you may find them in the paths less traveled by civilized witches and wizards\”. You’ll have to keep looking.', ['Go next door to Florean Fortescue\’s Ice Cream shoppe. The search for ingredients has you in need of a snack.', 'floreanFortescue'], ['Flourish and Blots. They sell books, maybe they also sell candles?', 'flourishBlots'], ['Go back to the Leaky Cauldron', 'leakyCauldron'], ['Return to the 2nd floor girls lavatory', 'home']);

let floreanFortescue = new LocationFeature('floreanFortescue', 'Florean Fortescue\’s Ice Cream', 'It has been such a long morning and Esmeralda is looking mournfully towards the Ice Cream shoppe. You decide you could both use a scoop. You purchase two cones of lemon drop sherbet and sit outside the shop at a table with a green striped umbrella. As you eat your ice cream, and hold Esmeralda\’s cone for her, you notice a disreputable looking wizard in wrinkled grey robes skulking in the shadows by Gringotts Wizarding Bank. You aren\’t sure you want to talk to him but he does look like he would know where to find the more controversial potion ingredients. You take one last bite of your ice cream and rush Esmeralda across the street towards the grey figure. Before you can get to him he ducks down an alley to the right of the bank. It looks really dark and scary but this is your first good lead so you follow him. Esmeralda\’s hooves are clicking loudly on the cobblestones of the deserted road. The wizard notices you following and turns around with his wand raised. You quickly duck into an opening on the left and begin to jog. The lane ends and spits you out in an even darker alley that stretches out into the shadows in both directions. The sign for the shop in front of you reads Shrunken Heads. You need to decide which way to go', ['Left', 'poisonousCandles'], ['Right', 'giantSpiders'], ['Go back to the Leaky Cauldron', 'leakyCauldron'], ['Return to the 2nd floor girls lavatory', 'home']);

let giantSpiders = new LocationFeature('giantSpiders', 'Giant Spiders', 'You decide to go right, despite Esmeralda\’s protestations, and look up at a shop that looks long abandoned with a sign reading Giant Spiders. Maybe this would have been a good place to get Acromantula Webbing if it hadn\’t gone out of business. Unfortunately the only webbing you see in the windows appears to belong to regular sized spiders so you are going to have to try your luck elsewhere.', ['Go back to the left', 'poisonousCandles'], ['Another ice cream is sounding really good right now', 'flourishBlots'], ['Go back to the Leaky Cauldron', 'leakyCauldron'], ['Return to the 2nd floor girls lavatory', 'home']);

let poisonousCandles = new ObjectLocationFeature('poisonousCandles', 'Poisonous Candles', 'Your heart starts beating rapidly when you read the name painted on the window of the shabby looking shop ahead. Poisonous Candles sounds like a place that might have just what you came for. As you approach the door you notice a handwritten note on the door that says \“Closed for lunch. Back in 30 minutes\”. You don’t want to hang out in this freaky alley waiting and it might not be a good idea to be seen buying goods from a place like this. You look down at your friends desperate face and realize you have no other choice. You are going to have to break in, get the candle, and get back to Hogwarts. You\’ll have to be in and out before the alarm charm that is likely placed on the door alerts the shopkeeper and you get caught.', ['You try the only unlocking charm you know, ironically also known as the \“theif’s friend\”', 'alohomora'], ['Amazingly the charm works and you stick your hand in the door, snatching the first candle you touch and leaving a gold coin in it\’s place. Hopefully one gold galleon is enough! You and Esmeralda dart into the shadows just as a young pox covered wizard apparates on the doorstep of the shop and runs inside to look for the intruder. You grab your pig and race for the Leaky Cauldron!', 'candle']);



